add_cash = "💵 Добавить приход"
check_salary = "🏦 Посмотреть ЗП"
average_receipt = "🧾 Средний чек"

pervichka = "pervichka"  # Callback с кнопки "Первичка"
garant = "garant"  # Callback с кнопки "Гарант"
holod = "holod"  # Callback с кнопки "Холод"
artem = "artem"  # Callback с кнопки "Артём"
clean_money = "cleanmoney"  # Callback с кнопки "Чистые деньги"
non_profile = "nonprofile"  # Callback с кнопки "Непрофиль"
class_a = "A"
class_b = "B"
